[package]
name = "bulk_chacha20_poly1305_ui_v2"
version = "0.1.0"
edition = "2021"

[dependencies]
chacha20poly1305 = "0.10"
argon2 = "0.4"
rand = "0.8"
walkdir = "2.3"
anyhow = "1.0"
hex = "0.4"
dialoguer = "0.10"
